### ISSUE TITLE
Rename config.js and lang/*.js to *.json

### ISSUE THREAD

**Issue by XhmikosR** [cloudflare/Cloudflare-WordPress#154]
Since those files aren't really JavaScript files, but JSON files, it would be much clearer if they used the right file extension.

**Comment by jwineman** [comment]
Hey,

I know @thellimist has been replying to a few of these.  I've been slow to reply because its Thanksgiving here in the U.S.  We should be able to reply to everything starting next week.

While I agree these files _should_ be .json unfortunately they have to be .js because [cloudflare/cloudflare-cpanel](https://github.com/cloudflare/CloudFlare-CPanel) doesn't recognize .json files..  cPanel serves 500 errors if we request them.  

Since we share code between all these plugins we have to support the lowest common denominator for stuff like this.

Thanks,
John

**Comment by XhmikosR** [comment]
Hey.

No worries, it's also weekend so there's no hurry :)

Now, about this, I understand completely. Thought, I have to say, it's weird that cPanel does this, but maybe it's one of their security measures.

Either way, it's no big deal, it just didn't seem right to me so I thought I'd bring it up.
