### ISSUE TITLE
html5shiv.min.js?ver=3.7.3 is server pushed when it shouldnt

### ISSUE THREAD

**Issue by gabu69** [cloudflare/Cloudflare-WordPress#175]
If i activate server push via wp-config.php:
`define('CLOUDFLARE_HTTP2_SERVER_PUSH_ACTIVE', true);`

This file will be pushed and downloaded when it shouldnt:
`<!--[if lt IE 9]><script type='text/javascript' src='https://www.site.com/wp-content/themes/genesis/lib/js/html5shiv.min.js?ver=3.7.3'></script><![endif]-->`

**Comment by thellimist** [comment]
The plugins solution with HTTP2 Server Push is a general solution to work with every website since we don't have enough information what the website needs to push.

You can check the [source code](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/HTTP2ServerPush.php). If there are improvements you can do which would work for everyone, feel free to contribute.

Alternatively, you can edit the code in your local environment. Just be aware that if you change the plugin code, in the next update your changes will disappear

**Comment by olilutz** [comment]
Hey @thellimist,
Server Push works well at my website. As above I have unwanted scripts and styles that get pushed because of the general solution. I'm new to php and wordpress. Can you tell me where and how I can change the php code so only scripts and styles that I want will get changed. I use autoptimize for bundling the css and I would like to change that only this file and some images will get pushed. Right now the plugin does push all previously bundled css so it's loaded twice

Thanks in advance

**Comment by thellimist** [comment]
https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/HTTP2ServerPush.php#L37-L41

Before line 37 you can add a if case to ignore some URL's.  This is not a good solution since every time the plugin update it'll get refreshed to the original code. 

You can use `error_log()` function to print `esc_url(self::http2LinkUrlToRelativePath($preload_src))` and `sanitize_html_class(self::http2LinkResourceHintAs(current_filter()))`. See what are useful for you and ignore those which are not. 

Sorry I didn't think of people customizing this feature while developing it. 

If you want, you can contribute by making the feature usable for a more general user base.

**Comment by jwineman** [comment]
@olilutz could you also let us know why you don't want the file included?  HTTP2 only affects how your page loads, not how it executes so I'm having trouble thinking of an edge case where you would want to exclude a file.

**Comment by olilutz** [comment]
@jwineman I try to explain what I want to achieve. I created a website and then I want it to load faster. I had about 20 css files that get loaded from theme and wordpress and so on. I installed the plugin autoptimize and all the css files were bundled in an autoptimize.css file. So there was only one css file to load which resulted in far better page load time. Now I installed the server push from cloudflare. When I check in chrome developer options network tab, server push works but it loads all 20 css files and the autoptimize.css file. Load time of each single was amazing but all together it's more bytes to load and slower all together. So I want to exclude all the 20 css files from header links preload and only let the bundled autoptimize.css file get pushed and some other image files.

**Comment by jwineman** [comment]
What if you disable the autoptimize plugin?  The benefit of HTTP2 is it loads files in parallel, removing the need for bundling.  In theory HTTP2 should be able to load 20 small CSS files faster than HTTP can load one large CSS file.  

It sounds like you're loading your CSS twice, the HTML markup should either be including the 20 CSS files OR the one large bundled CSS file.

**Comment by olilutz** [comment]
Actually I did this and it wasn't faster. Checked it dozens of times. Problem is all registered css files will be loaded including adminbar and stuff that isn't even needed for normal visitor. Now these files are all visible in the network timeline. Wasn't visible when I only have one css file.
One more thing how can I extend the preload link creation? As mentioned above I would like to add some images to server push but don't know how and where to add the links permanently.

**Comment by thellimist** [comment]
> Actually I did this and it wasn't faster

It depends on where the bottleneck is. Best way is to figure out the bottleneck and optimize that. Every website owner should figure that out themselves. 

> Problem is all registered css files will be loaded including adminbar and stuff that isn't even needed for normal visitor

If you enter as an admin the css will be sent regardless of you using autoptimize or not. autoptimize will just merge those CSS into the same file. 

> Now these files are all visible in the network timeline. Wasn't visible when I only have one css file.
If it's faster you shouldn't care if there are billion files or 1 file in the network timeline. There's no direct correlation. 

> One more thing how can I extend the preload link creation?
You need to add the following header `Link: </image.jpg>; rel=preload; as=image`.

You need to edit multiple places. 
1) https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/HTTP2ServerPush.php#L28 add new filter. Figure out which filter will allows to traverse images. If not filter exists create one which scans HTML and traverses images. 
2) https://github.com/cloudflare/Cloudflare-WordPress/blob/master/src/WordPress/HTTP2ServerPush.php#L101 edit this part to add the text 'image' where `.. as=image`

This is a generic solution. For simple solution you can just manually add the `Link` you want to be pushed `initHooks` functions.
