### ISSUE TITLE
Automatic cache purge doesn't work when switching a page from public => private

### ISSUE THREAD

**Issue by mispy** [cloudflare/Cloudflare-WordPress#200]
This plugin is usually awesome and works well for purging the CF cache when a post is updated. However it doesn't do it if you change the visibility of an existing page from public to private-- the cached public version stays around.

(I imagine this bug is because it thinks "oh, I don't need to purge the cache for this private post" without taking into consideration that it used to be public a moment ago)

**Comment by thellimist** [comment]
We're purging by URL only when these hooks are triggered https://github.com/cloudflare/Cloudflare-WordPress/blob/master/cloudflare.loader.php#L82-L86

The purging happens in this function https://github.com/cloudflare/Cloudflare-WordPress/blob/9a82610a14fe27996c2f92779629aaa20f9d9f1f/src/WordPress/Hooks.php#L128

[Contributions](https://github.com/cloudflare/Cloudflare-WordPress/blob/master/CONTRIBUTING.md) are always appreciated.

**Comment by Inwerpsel** [comment]
This was not actually fixed in https://github.com/cloudflare/Cloudflare-WordPress/pull/206. If you publish a post, then afterwards change the status to "private", it will run the purge action. But the action itself checks the status of the post and bails out unless it's either "publish" or "trash". https://github.com/cloudflare/Cloudflare-WordPress/blob/9a82610a14fe27996c2f92779629aaa20f9d9f1f/src/WordPress/Hooks.php#L137-L142

I created a PR to address this by adding "private" to those statuses, but also a check to not purge those unless the status was changed from "public". https://github.com/cloudflare/Cloudflare-WordPress/pull/365
