### ISSUE TITLE
IPv6 requests

### ISSUE THREAD

**Issue by samip5** [cloudflare/Cloudflare-WordPress#237]
Hello,

Is there any reason why the IP address which gets saved to a form is Cloudflare's when it should be the user's?

Cloudflare's IPv6 address is visible as the form submitter's IP address.

The IP:
`2405:8100:8000:5ca1:0:0:98:b201`

**Comment by garrettgalow** [comment]
Since Cloudflare is a proxy, by nature the connecting IP to your server will be a Cloudflare IP when it proxies your traffic. Cloudflare does provide a `CF-CONNECTING-IP` header that will contain the original end user IP.

The exact answer as to how to get that IP into your server or application logs depends on specifics of your environment. You can find various support articles about restoring [visitor IPs here](https://support.cloudflare.com/hc/en-us/sections/200805497-Restoring-Visitor-IPs?page=1#articles).
