### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by tillkruss** [cloudflare/Cloudflare-WordPress#251]
I'm getting error on PHP 7.4:

```
Notice: Trying to access array offset on value of type null in plugins/cloudflare/src/WordPress/Hooks.php on line 249
```

**Comment by rmens** [comment]
I can confirm this error. Also, the cache is not purged any more when a post status changes. This worked on PHP 7.3 but not on 7.4 anymore.

**Comment by tillkruss** [comment]
@brandomeniconi: Could you have a look at this?

**Comment by brandomeniconi** [comment]
Hi,
thanks calling me out, I've tried to see where the issue by looking at the code, but didn't had time to setup a `php7.4` env to verify it. 

The issue with php 7.4 is that it now raises a `notice` if you try to do this:
```php
$configVal = null;
return $configVal[0];
```
while before it simply returns `null`.

I suppose that this line is returning `null` and triggers the notice:
https://github.com/cloudflare/Cloudflare-WordPress/blob/a46a7cb5fff30fd20a1c53a9f507b5bd184b2f8e/src/WordPress/Hooks.php#L248

because that traces back to a WP's `get_option` call that when there is no value in the DB it returns null by default. So probably the solution is to catch the `null` value early, something like this:

```php
    protected function isPluginSpecificCacheEnabled()
    {
        $cacheSettingObject = $this->dataStore->getPluginSetting(\CF\API\Plugin::SETTING_PLUGIN_SPECIFIC_CACHE);

        if (  $cacheSettingObject === null || !isset($cacheSettingObject[\CF\API\Plugin::SETTING_VALUE_KEY]) ){
            return false;
        }

        $cacheSettingValue = $cacheSettingObject[\CF\API\Plugin::SETTING_VALUE_KEY];

        return isset($cacheSettingValue) && $cacheSettingValue !== false && $cacheSettingValue !== 'off';
    }
```

If you want to try to edit the code live and let me know, I found little tricky to debug this plugin because it can be full-activated on dev environments. I'll try in the next weeks and if the solution works, I can write a PR.

**Comment by tillkruss** [comment]
@brandomeniconi: I've added a PR.

**Comment by brandomeniconi** [comment]
> @brandomeniconi: I've added a PR.

Nice thanks, have you tested it and it works?

**Comment by tillkruss** [comment]
Yes, it works. Ideally we'd use the `??` operator, but that would require PHP 7+.
