### ISSUE TITLE
Any way for APO to cache the index page?

### ISSUE THREAD

**Issue by wichtounet** [cloudflare/Cloudflare-WordPress#319]
Hi, 

I am currently trying APO with this plugin and everything seems to be working well. 
However, by default index pages and feed pages are not cached. I had to use extra page rules to set them to Cache Everything. 

So two questions:
1) Is there a way to tell APO to cache these dynamic pages?
2) What is the advantage of using APO compared to simply using a Cache Everything Page Rules for every pages?

Thanks!

**Comment by garrettgalow** [comment]
Hi, @wichtounet 

For (1) do those pages end in .html or have content headers as such? APO only caches html page, so if we don't recognize them as such then they won't get cached. This is a bit of a shot in the dark as its hard to ascertain what is happening without  further details.

For (2) - APO does a few things on top of just using cache everything page rules

1. bypasses cache on cookies for admins, logged in users, and other cases where you wouldn't want to cache dynamic content - this is big as just setting the cache everything page rule can lead to data leaks of serving cached authenticated pages.
2. keeps the content in our KV storage, so any of our colos can pull it from there instead of going to origin
3. We hook into WordPress to send update events of content which helps ensure if you, for example, change a post then we purge the cache and reduce the time we would serve stale content.

**Comment by wichtounet** [comment]
Hi,

Thanks for your answer!

1) The index and blog pages have `content-type: text/html` header. The
feeds do not have HTML.

2) 1 and 3 can be taken care of by not caching any logged-in, data, but I
agree that it's a pain. 2 is indeed a big advantage. However, this is only
an advantage for the HTML, not for the static resources that are still not
handled by KV Workers.

I am going to continue to try it, but I did not see any sizeable difference
compared to just running Cache Everything so far.

>

**Comment by sejoker** [comment]
I'm going to close the ticket, feel free to ask APO related questions in http://community.cloudflare.com/
