### ISSUE TITLE
APO Not disabling via Cloudflare Plugin

### ISSUE THREAD

**Issue by SpidermanPuddin** [cloudflare/Cloudflare-WordPress#343]
Tried several times to disable APO via the plugin and it will not disable. Upon refresh, it is active again.

**Comment by orenwolf** [comment]
I had this issue, it turned out that the WAF settings for our domain were too strict, as the plugin uses HTTP commands (like PATCH) that aren't commonly used on most Wordpress installs, and so WAF rules like "block all requests except GET/HEAD/POST" will break the plugin in wonderfully strange ways.

**Comment by SpidermanPuddin** [comment]
Just tried disabling all the WAF settings via CloudFlare. It still didn't allow the plugin the disable APO.

**Comment by sejoker** [comment]
I've no idea why it could happen, as the solution of last resort, you can disable APO in Cloudflare Dashboard's Speed page (under Optimization tab).

**Comment by sejoker** [comment]
I'm going to close the ticket, if you still have an issue feel free to raise customer support ticket and post # here.
