### ISSUE TITLE
Suggestion: Add Cloudflare Images features

### ISSUE THREAD

**Issue by aheckler** [cloudflare/Cloudflare-WordPress#407]
Yesterday Cloudflare [announced the Images beta](https://blog.cloudflare.com/announcing-cloudflare-images-beta/). This would be neat to build into the WordPress plugin, and perhaps package into the existing Automatic Platform Optimization feature. After all, with APO, you are already caching media at the edge, so it makes sense to take the next step and just store the images directly.

**Comment by erikdemarco** [comment]
I disagreee. We should at least make this cloudflare plugin as simple as possible. If you add more and more features it will make cloudflare plugin more prone to error due to many different plugin combinations. You know cache plugin usually cause the most complain/trouble in WP. If developer insist to add this feature at least wait until the plugin reviews on WP site getting better. If you add it too soon I'm sure 100% this plugin will get many more negative reviews in turn making cloudflare reputation doing downhill.

**Comment by jacobbednarz** [comment]
not adding new features because of instability concerns isn't a viable reason nor would it be the deciding factor here. @erikdemarco if you have issues due to this plugin, please raise a reproducible bug report and we can take a pass at fixing it. i can't guarantee we will fix everything but we can't address issues we aren't aware of.

@aheckler i'll flag the PM to consider this one for the roadmap if it's not already on there.

**Comment by yogeshbeniwal** [comment]
@jacobbednarz Thanks for flagging it to PM. Just checking if this is in line for consideration or in development. Currently a user of APO on few website and can transfer all other to APO if image feature comes bundled with APO. Currently used third party plugin add too much JS and not so good for performance

**Comment by yogeshbeniwal** [comment]
Reopen
