### ISSUE TITLE
Unauthorized error when attempting to purge cache for individual pages

### ISSUE THREAD

**Issue by toddbenton** [cloudflare/Cloudflare-WordPress#497]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

6.0.3

### Cloudflare-WordPress version

4.11.0

### PHP version

8.0

### Expected result

Expected to be able to clear cache of individual pages. 

### Actual result

Unauthorized error message appears at the bottom of the page. Purge everything works fine. Purge individual pages from Cloudflare website also works fine. 
![Screen Shot 2022-10-26 at 9 44 33 AM](https://user-images.githubusercontent.com/10078303/198355445-91ad76d7-74ab-4e2a-a727-f6f5b9f348f0.png)

### Steps to reproduce

1. Go to purge cache section of plugin homepage in WordPress dashboard. 
2. Click Purge Cache button
3. Choose Purge Individual Files
4. Enter any url on the website.
5. Unauthorized message appears at the bottom of the screen (see screenshot in the previous section)

**Comment by zaidoonhad** [comment]
Hi @toddbenton we would like more information in order to be able to debug. Can you create a support ticket here: [support.cloudflare.com](http://support.cloudflare.com/). And include the API request you are sending (or the plugin is sending in this case) and the api response, you can attempt to purge via API directly and include the call and the response if you are not able to see the debug logs for the plugin. The api for purging cache is documented here: https://api.cloudflare.com/#zone-purge-files-by-url

Once you do that, please include the ticket number here and we can look at this for you. Thanks!
