### ISSUE TITLE
APO Cache is Not Cleared on Tablet

### ISSUE THREAD

**Issue by jfireman** [cloudflare/Cloudflare-WordPress#500]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

6.1.1

### Cloudflare-WordPress version

4.11.0

### PHP version

7.4.27

### Expected result

APO clear cache after content update for all device type including tablet

### Actual result

Only desktop and mobile version cache is cleared, tablet version still display old content

### Steps to reproduce

Activate the plugin
Activate APO
Activate "Cache by device type"
View content to be updated on mobile, desktop, and tablet
Update content
Reload and view the updated content on mobile, desktop, and tablet

### Additional factoids

I've tested this issue with iPad (emulated), Android tablet (emulated and on device), and Kindle Fire HDX (emulated) and all are displaying old contents.

For now, I set a page rules in Cloudflare to bypass all cache for tablet only in order to show the fresh content.

### References

The issue is similar to this one: https://github.com/cloudflare/Cloudflare-WordPress/issues/404 but this time it's for tablet device

**Comment by elliott-stocks** [comment]
I'm able to replicate this too, but it seems that the cache is eventually purged if you refresh the desktop version a few times.

Steps to replicate -

1. Publish a post and view in incognito mode
2. Emulate an iPad in Chrome devtools
3. Update the post title
4. Refresh the incognito window
5. The page title isn't updated
6. Disable emulate mode and refresh again - the title is updated (as it's desktop)
7. Switch back to emulate mode and refresh - the title is now updated

I'm assuming that the "default" cache key is always desktop, which is why there's no logic for purging cache specifically for desktop in the plugin. As of now there's only a method for clearing the mobile cache.

PR opened in #505.

**Comment by JustinFreid** [comment]
Does changing the Edge Cache TTL to be very short help fix this issue even if it puts slightly more load on the Origin?
